services:
  db:
    image: timescale/timescaledb-ha:pg17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/home/postgres/pgdata/data
      - ./docker/tsdb/100_setup_db.sql:/docker-entrypoint-initdb.d/100_setup_db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 1s
      timeout: 5s
      retries: 50

  app:
    build:
      context: .
      target: builder
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "3020:3001"
    volumes:
      - ./migrations:/app/migrations
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
    command: npm run watch:http


volumes:
  db_data:
