name: Build Docker - Feature Branch Push
on:
  push:
    branches-ignore:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Workflow
        uses: timescale/workflow-dispatch-action@main
        with:
          github-token: ${{ secrets.GH_AGENTS_PAT }}
          owner: timescale
          repo: tiger-agents-deploy
          workflow_id: build.yaml
          ref: 'main'
          inputs: '{"repository": "tiger-docs-mcp-server", "sha": "${{ github.sha }}"}'
