name: Ingest Timescale Docs
on:
  schedule:
    - cron: '0 2 * * 0'
  workflow_dispatch:

jobs:
  ingest:
    name: Ingest Timescale Docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ingest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install python dependencies
        run: uv sync

      - name: Ingest Timescale docs for dev
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PGHOST: ${{ secrets.PGHOST }}
          PGPORT: ${{ secrets.PGPORT }}
          PGDATABASE: ${{ secrets.PGDATABASE }}
          PGUSER: ${{ secrets.PGUSER }}
          PGPASSWORD: ${{ secrets.PGPASSWORD }}
        run: uv run python timescale_docs.py

      - name: Ingest Timescale docs for prod
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PGHOST: ${{ secrets.PROD_PGHOST }}
          PGPORT: ${{ secrets.PROD_PGPORT }}
          PGDATABASE: ${{ secrets.PROD_PGDATABASE }}
          PGUSER: ${{ secrets.PROD_PGUSER }}
          PGPASSWORD: ${{ secrets.PROD_PGPASSWORD }}
        run: uv run python timescale_docs.py
